# Generated by Django 3.2.2 on 2021-06-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSPfrontend', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
