# Generated by Django 3.2.2 on 2021-06-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSPfrontend', '0008_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
