# Generated by Django 3.2.2 on 2021-06-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSPfrontend', '0011_alter_info_member2name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='member2name',
            field=models.CharField(default='koi', max_length=122),
        ),
    ]
