# Generated by Django 3.2.2 on 2021-06-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSPfrontend', '0014_alter_info_member2name'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='teamid',
            field=models.CharField(default='ITS21001', max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='aboutteam',
            field=models.CharField(default='Technologic is a Platinum HubSpot Agency Partner who positions themselves as an extension of their clients marketing teams. For that reason, they showcase the people on their staff to highlight the humans behind the brand.Whats pleasing about this particular meet the team page is the matching blue backgrounds and cool palette.The grid design provides a modern feel, and if you click on one of the faces,a box will open with more information about the team member, including their bio, credentials, and social profiles.', max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='member1email',
            field=models.CharField(default='saakshi@gmail.com', max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='member1name',
            field=models.CharField(default='saakshi .s.', max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='member2email',
            field=models.CharField(default='vinit@gmail.com', max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='member2name',
            field=models.CharField(default='vinit sharma', max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='member3email',
            field=models.CharField(default='priyanka@gmail.com', max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='member3name',
            field=models.CharField(default='priyanka ghandhi', max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='teamleaderemail',
            field=models.CharField(default='william@gmail.com', max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='teamleadername',
            field=models.CharField(default='william james', max_length=122),
        ),
    ]
